### ISSUE TITLE
Consistency+ Forge 1.19.2 - 0.5.1 Crashing on launch

### ISSUE THREAD

**Issue by SplitCoder** [ConsistencyPlus/ConsistencyPlus#153] opened 2023-02-21 06:23 UTC
**Describe the bug:**
A clear and concise description of what the bug is. Include as much information as you can.  Images are often helpful, especially screenshots of the F3 debug menu.

**Versions:**
Minecraft version: Consistency+ Forge 1.19.2 - 0.5.1
C+ version:
Fabric API / QSL / Forge version: Forge

**Other mods:**
List all mods that you're using; could be in the form of a list of the filenames, a crash report list, a screenshot of
the mods folder, etc. Just make sure all mods used are known!
            Only mod in folder
**Logs:**
*Even if the game does not crash they may be useful!*
Please provide the following logs:
From .minecraft/logs :  "latest.log" as well as "debug.log" if it exists. From .minecraft : "launcher_log" as well as a
file that starts with "hs_err" if it exists. Note: Double check that the logs are from the correct time. ex, don't give
us a log from a month ago because you forgot to check the date.
            Exit Code 1. No log is created
**To Reproduce:**
Steps to reproduce the behavior. Format it as a numbered list of steps.

1. 1.19.2 Forge 43.2.0
2. Add only Consistency+ Forge 1.19.2 - 0.5.1
3. Launch game

**Expected behavior:**

**Screenshots:**
If applicable, add screenshots to help explain your problem. https://screenshot.help/

**Additional info:**
Add any other information that might be needed.

**Comment by Cart3r1234** [comment] 2023-04-12 23:15
> Exit Code 1. No log is created

Are you sure there isn't a log created in the normal logs folder?  There may always not be a crash log, but there should always be a normal log, which may help in resolving the issue.

**Comment by Cart3r1234** [comment] 2023-05-22 17:57
Closing this due to lack of response, being unable to reproduce, and because we've released an update.

**Closed as completed by Cart3r1234** 2023-05-22 17:57 UTC
Labels: Bug/Issue, Question/Information Needed
