### ISSUE TITLE
Mossy Blackstone Brick Stairs inner corner missing

### ISSUE THREAD

**Issue by Adrikoe** [ConsistencyPlus/ConsistencyPlus#17] opened 2021-03-31 17:01 UTC
The inner corner of the Mossy Blackstone Brick Stairs is missing a texture/model.

Minecraft version: 1-16-5
Fabric API version: 0.31.0

Other mods:
Optifine
Optifabric

Steps to reproduce the behavior. Format it as a numbered list of steps.
1. place 3 Mossy Blackstone Brick Stairs to form an inner corner piece
2. look at the inner corner

a normal looking inner corner piece

![grafik](https://user-images.githubusercontent.com/57302287/113182719-84a0be80-9253-11eb-8d2f-f65d812bbbbd.png)

**Comment by Siuolthepic** [comment] 2021-03-31 18:21
Are you using 0.1 or 0.2? If 0.1 please test this on 0.2, our project lead recalls fixing this, but if it aint fixed we can fix it in 0.3

**Comment by Siuolthepic** [comment] 2021-04-01 01:42
I am closing this issue as I am not able to reproduce this on latest dev build

**Closed by Siuolthepic** 2021-04-01 01:42 UTC
Labels: bug, question
