### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'consistency_plus'

### ISSUE THREAD

**Issue by cssmc** [ConsistencyPlus/ConsistencyPlus#84] opened 2021-11-28 23:23 UTC
BUG: **`Server crashes on startup`**
MCv: **`1.16.5`**
Lv: **`0.11.7 / 1.12.5`**
Mv: **`consistency_plus-fabric-0.4.2+RC.1+1.16`**
fAPI: **`0.42.0`**
Av: **`architectury-1.25.36-fabric`**

**Other:**
1. [Modlist](https://github.com/cssmc/modpack/blob/main/modpack/modlist.md)
2. [Crashlog_01](https://pastebin.com/1gSu6s2c)
3. [Crashlog_02](https://pastebin.com/pS5RGpkS)

**Additional info**
Porting to the ǝƃɹoɟ was a bad idea.

Regards
CSSmc

**Comment by TropheusJ** [comment] 2021-11-28 23:25
Don’t know why the log says caused by C+, the actual error clearly points to mousewheelie. Try without it.

**Comment by TropheusJ** [comment] 2021-11-28 23:27
On the client, at least. The second crash log is caused by a known issue that somehow slipped through, should be fixed soon

**Comment by wafflecoffee** [comment] 2021-11-28 23:29
> Porting to the ǝƃɹoɟ was a bad idea.

We know, that's why we did it

**Comment by cssmc** [comment] 2021-11-28 23:31
You are fast, thanks for the answer's, yes I added logs without mousewheelie, waiting for the fix, best regards

**Comment by Siuolthepic** [comment] 2021-11-28 23:43
Found the issue and fixed it hopefully, gonna send it in shortly, you mind testing it?

**Comment by Siuolthepic** [comment] 2021-11-28 23:48
[consistency_plus-0.4.2+RC.1+1.16-fabric.zip](https://github.com/ConsistencyPlus/ConsistencyPlus/files/7614646/consistency_plus-0.4.2%2BRC.1%2B1.16-fabric.zip)
@cssmc Try this

**Comment by cssmc** [comment] 2021-11-29 11:35
the problem is solved thank you!

**Closed** 2021-11-29 19:50 UTC
Labels: Bug/Issue

**Comment by IMS212** [comment] 2021-11-29 20:04
cringe
