### ISSUE TITLE
Game crashes on craft in stonecutter

### ISSUE THREAD

**Issue by Punkin-GH** [ConsistencyPlus/ConsistencyPlus#141] opened 2022-12-18 04:57 UTC
**Describe the bug:**

When using the stonecutter to make other blocks, the game immediately crashes

**Versions:**

Minecraft version: 1.19.2
C+ version: 0.5.1
Fabric API / QSL / Forge version: Quilt Loader 0.18.1 Beta 23

**Other mods:**

(See crash report/logs)

**Logs:**

[latest.log](https://github.com/ConsistencyPlus/ConsistencyPlus/files/10253217/latest.log)

[crash-2022-12-17_22.55.42-client.txt](https://github.com/ConsistencyPlus/ConsistencyPlus/files/10253218/crash-2022-12-17_22.55.42-client.txt)

**To Reproduce:**

1. Use the stonecutter
2. Craft a block
3. See error

**Expected behavior:**

For the stonecutter to output the selected block

**Screenshots:**
N/A

**Additional info:**
N/A

**Comment by Cart3r1234** [comment] 2022-12-18 05:01
Can confirm, discovered this myself about 20 minutes ago while playing on a quilt server.  We're looking into it!

**Comment by TropheusJ** [comment] 2022-12-18 05:19
duplicate of #137

**Closed by TropheusJ** 2022-12-18 05:19 UTC
Labels: Bug/Issue, In Progress, High Priority
